name: SonarCloud CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: Set up Python if needed for SonarPython analysis
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      # Set up Node.js and Vitest (Frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install frontend dependencies and run tests
      - name: Install frontend dependencies and run tests
        run: |
          cd frontend
          npm install
          npm run test -- --coverage  # Ensure Vitest generates coverage

      # # Install Python dependencies and run backend tests
      # - name: Install Python dependencies and run backend tests
      #   run: |
      #     cd backend
      #     pip install -r requirements.txt
      #     pip install pytest coverage
      #     pytest tests --cov=. --cov-report=xml --cov-report=term-missing  # Backend coverage report for Python
      #   env:
      #      DATABASE_URL: "sqlite:///:memory:"
      # Run SonarCloud scan with coverage report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
