name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Tests and Analyze with SonarCloud
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov python-dotenv

      - name: Create .env file
        run: |
          {
            echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}"
            echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}"
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
            echo "ALGORITHM=${{ secrets.ALGORITHM }}"

          } > backend/.env
        shell: bash

      - name: Remove existing coverage.xml
        run: |
          rm -f backend/coverage.xml

      - name: Run tests with coverage
        run: |
          pytest backend/tests 

      - name: Show coverage.xml contents
        run: |
          ls -l coverage.xml
          head -n 30 coverage.xml || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}